### PR TITLE
Sprint 4 Release Notes

### PR DESCRIPTION
**Pull request by waffy1901**

### CODE REVIEW

**Review by Carson21 — COMMENTED** [review]
I wouldn't say that we encrypted the username and password, just moved them to be in environment variables

**Comment by p-zach** [comment]
^

**Review by john-baute — COMMENTED** [review]
Yeah just what Carson said, otherwise looks good

**Review by Carson21 — APPROVED** [review]

**Review by p-zach — APPROVED** [review]

**Review by jonnamorrison — APPROVED** [review]
looks good!

**Review by solomonmcharo28 — APPROVED** [review]
Looks Great Waffy

**Pull request merged**
