### PR TITLE
Added odbc_list.py and moved example data to its own folder

### PR DESCRIPTION
**Pull request by Carson21**

### CODE REVIEW

**Review by waffy1901 — APPROVED** [review]
Good call in moving the example data to its own folder and creating a separate file for odbc_list.

**Review by waffy1901 — APPROVED** [review]
Good call in moving the example data to its own folder and creating a separate file for odbc_list.

**Review by solomonmcharo28 — APPROVED** [review]
Changes look great to me.

**Review by jonnamorrison — APPROVED** [review]
looks good!

**Pull request merged**
